# Generated by Django 4.1.4 on 2022-12-21 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("alo", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Contract",
            new_name="Contact",
        ),
    ]
