# Generated by Django 4.1.4 on 2022-12-21 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("alo", "0002_rename_contract_contact"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Contact",
            new_name="Contract",
        ),
    ]
